//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeBetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid CommentId { get; set; }
        public string Body { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
