//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeBetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Comment = new HashSet<Comment>();
            this.UsersInTask = new HashSet<UsersInTask>();
        }
    
        public System.Guid TaskId { get; set; }
        public Nullable<byte> State { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> UseId { get; set; }
        public Nullable<int> TaskType { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UsersInTask> UsersInTask { get; set; }
    }
}
