//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeBetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comment = new HashSet<Comment>();
            this.Task = new HashSet<Task>();
            this.UsersInTask = new HashSet<UsersInTask>();
        }
    
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public Nullable<int> Rating { get; set; }
        public string KloutId { get; set; }
        public string DnaId { get; set; }
        public string PasswordHash { get; set; }
        public string VKId { get; set; }
        public string FacebookId { get; set; }
        public string GoogleId { get; set; }
        public Nullable<bool> Banned { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Task> Task { get; set; }
        public virtual ICollection<UsersInTask> UsersInTask { get; set; }
    }
}
